wandb:
  project: ml_pipeline_mvp_iris
  entity: heschmat

data:
  dir: assets
  filename: data.csv
  url: https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv

mlflow:
  experiment: iris_pipeline_experiment
